/**
 * Generates .env.docker with PDS secrets required to run the local atproto PDS.
 * Run once: npm run pds-init
 *
 * All generated secrets are cryptographically random. Safe to regenerate any time
 * (existing PDS data becomes inaccessible if keys change, so don't re-run on an
 * existing PDS unless starting fresh).
 */

import { randomBytes } from 'crypto';
import { existsSync, writeFileSync } from 'fs';
import { resolve } from 'path';

const OUT = resolve(process.cwd(), '.env.docker');

if (existsSync(OUT)) {
  console.error(`\n❌  .env.docker already exists. Delete it first if you want to regenerate.\n`);
  console.error(`    rm .env.docker && npm run pds-init\n`);
  process.exit(1);
}

/** 32-byte hex string (secp256k1 private key format required by PDS) */
const k256 = () => randomBytes(32).toString('hex');

/** 32-byte hex string (used for DPOP secret) */
const hex32 = () => randomBytes(32).toString('hex');

/** 32-byte URL-safe base64 (used for JWT secret and admin password) */
const b64 = () => randomBytes(32).toString('base64url');

const content = `# Generated by: npm run pds-init
# DO NOT COMMIT — .env.docker is in .gitignore
#
# These secrets unlock your local atproto PDS. If you regenerate them,
# any existing data/ volume becomes inaccessible (keys won't match).
# Use: docker compose --profile pds up

PDS_HOSTNAME=localhost

# Private keys (secp256k1 — 64-char hex)
PDS_REPO_SIGNING_KEY_K256_PRIVATE_KEY_HEX=${k256()}
PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX=${k256()}

# Secrets
PDS_DPOP_SECRET=${hex32()}
PDS_JWT_SECRET=${b64()}
PDS_ADMIN_PASSWORD=${b64()}
`;

writeFileSync(OUT, content, 'utf8');

console.log(`\n✅  .env.docker created with fresh PDS secrets.\n`);
console.log(`    Start the full stack with:`);
console.log(`      docker compose --profile pds up\n`);
console.log(`    PDS admin panel: http://localhost:2583/xrpc/com.atproto.server.describeServer\n`);
